name: Run tests

on: [push, pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make lint

    - name: Run tests
      run: make test

    - name: Run backend tests
      run: make test-backends
